"""update domain table

Revision ID: 94a3245ad05c
Revises: bed7136b1a72
Create Date: 2025-06-03 07:43:21.910507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a3245ad05c'
down_revision = 'bed7136b1a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))
        batch_op.drop_column('domain_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('url')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
